from enum import Enum


class SourceType(str, Enum):
    CITIZEN = "CITIZEN"
    EMERGENCY_SERVICE = "EMERGENCY_SERVICE"
    SOCIAL_MEDIA = "SOCIAL_MEDIA"
    CCTV_SYSTEM = "CCTV_SYSTEM"
    AUTHORITY = "AUTHORITY"
    OTHER = "OTHER"


class IncidentType(str, Enum):
    FIRE = "FIRE"
    ACCIDENT = "ACCIDENT"
    MEDICAL = "MEDICAL"
    NATURAL_DISASTER = "NATURAL_DISASTER"
    PUBLIC_SAFETY = "PUBLIC_SAFETY"
    INFRASTRUCTURE = "INFRASTRUCTURE"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class InformationStatus(str, Enum):
    VERIFIED = "VERIFIED"
    UNVERIFIED = "UNVERIFIED"
    CONFLICTING = "CONFLICTING"
    OUTDATED = "OUTDATED"
    PROCESSING = "PROCESSING"


class Priority(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class AlertType(str, Enum):
    CRITICAL_INCIDENT = "CRITICAL_INCIDENT"
    CONFLICT_DETECTED = "CONFLICT_DETECTED"
    OUTDATED_INFORMATION = "OUTDATED_INFORMATION"
    MULTIPLE_REPORTS = "MULTIPLE_REPORTS"
    HIGH_PRIORITY = "HIGH_PRIORITY"
