"use client"

import { FlaskConical, RotateCcw, Play, CheckCircle2 } from 'lucide-react'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { PageHeading, Panel } from '../components/common/ui'
import { api } from '../services/api'

export function Demo() { const [state, setState] = useState<'idle' | 'loading' | 'offline' | 'done'>('idle'); const router = useRouter(); const load = async () => { setState('loading'); const result = await api.loadDemo() as { accepted?: boolean }; if (result.accepted) { setState('done'); window.setTimeout(() => router.push('/'), 800) } else setState('offline') }; const reset = async () => { setState('loading'); const result = await api.resetDemo() as { accepted?: boolean }; setState(result.accepted ? 'done' : 'offline') }; return <main className="page"><PageHeading eyebrow="Presentation mode" title="Demo scenario" description="Ask the backend to load or reset its synthetic scenario through the real processing pipeline. The frontend does not substitute expected results." /><div className="detail-grid"><Panel title="Control demo data"><div className="panel-body"><p className="muted" style={{ lineHeight: 1.55, marginTop: 0 }}>The scenario should include related Block A fire reports, a fire-status conflict, Gate 2 road-accident reports, and a road-clearance update. Returned results will be shown on the dashboard.</p><div style={{ display: 'flex', gap: 9, flexWrap: 'wrap' }}><button className="btn btn-primary" disabled={state === 'loading'} onClick={() => void load()}><Play size={14} /> {state === 'loading' ? 'Requesting…' : 'Load demo scenario'}</button><button className="btn btn-danger" disabled={state === 'loading'} onClick={() => void reset()}><RotateCcw size={14} /> Reset demo</button></div></div></Panel><Panel title="Backend processing"><div className="panel-body">{state === 'idle' && <div className="notice"><FlaskConical size={15} style={{ verticalAlign: 'middle', marginRight: 7 }} />Load calls <code>POST /api/demo/load</code>. This page only shows success after the backend confirms it.</div>}{state === 'loading' && <div className="loading">Waiting for backend demo response…</div>}{state === 'done' && <div className="notice"><CheckCircle2 size={15} style={{ verticalAlign: 'middle', marginRight: 7 }} />Backend operation completed. Opening the updated dashboard…</div>}{state === 'offline' && <div className="notice">The backend is unavailable or did not confirm this operation. No synthetic dashboard results have been created by the frontend.</div>}</div></Panel></div></main> }
