"use client"

import { useEffect, useMemo, useState } from 'react'
import { IncidentCard } from '../components/incidents/IncidentCard'
import { PageHeading } from '../components/common/ui'
import { api } from '../services/api'
import type { Incident, Severity } from '../types'

export function Incidents() { const [items, setItems] = useState<Incident[]>([]); const [severity, setSeverity] = useState('ALL'); const [status, setStatus] = useState('ALL'); const [type, setType] = useState('ALL'); const [confidence, setConfidence] = useState('ALL'); useEffect(() => { void api.getIncidents().then(setItems) }, []); const filtered = useMemo(() => items.filter((item) => (severity === 'ALL' || item.severity === severity) && (status === 'ALL' || item.status === status) && (type === 'ALL' || item.type === type) && (confidence === 'ALL' || (confidence === 'HIGH' ? item.confidence >= 80 : item.confidence < 80))), [items, severity, status, type, confidence]); return <main className="page"><PageHeading eyebrow="Incident register" title="All active incident information" description="Filter by operational significance, response status, evidence confidence, and incident type." /><div className="panel"><div className="panel-body filters"><select className="field" value={severity} onChange={(event) => setSeverity(event.target.value)}><option value="ALL">All severity</option>{(['CRITICAL','HIGH','MEDIUM','LOW'] as Severity[]).map((value) => <option key={value}>{value}</option>)}</select><select className="field" value={status} onChange={(event) => setStatus(event.target.value)}><option value="ALL">All statuses</option><option>ACTIVE</option><option>CONTAINED</option><option>RESOLVED</option><option>UNKNOWN</option></select><select className="field" value={type} onChange={(event) => setType(event.target.value)}><option value="ALL">All incident types</option>{[...new Set(items.map((item) => item.type))].map((value) => <option key={value}>{value}</option>)}</select><select className="field" value={confidence} onChange={(event) => setConfidence(event.target.value)}><option value="ALL">All confidence</option><option>HIGH</option><option>MODERATE / LOW</option></select></div></div><div className="incident-list" style={{ marginTop: 18 }}>{filtered.map((incident) => <IncidentCard key={incident.incident_id} incident={incident} />)}{!filtered.length && <div className="empty panel">No incidents match the current filters.</div>}</div></main> }
