"use client"

import { CheckCircle2, Link2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link } from '../components/common/Link'
import { PageHeading, Panel } from '../components/common/ui'
import { api } from '../services/api'
import type { Incident, IntelligenceMetrics } from '../types'

const flow = ['Incoming reports', 'Information extraction', 'Similarity analysis', 'Incident fusion', 'Evidence & claims', 'Conflict detection', 'Confidence', 'Consolidated incident']
export function Intelligence() { const [metrics, setMetrics] = useState<IntelligenceMetrics>(); const [items, setItems] = useState<Incident[]>([]); useEffect(() => { void Promise.all([api.getIntelligenceMetrics(), api.getIncidents()]).then(([nextMetrics, nextItems]) => { setMetrics(nextMetrics); setItems(nextItems) }) }, []); return <main className="page"><PageHeading eyebrow="Data fusion" title="Intelligence center" description="A transparent view of how related source reports become evidence-aware, consolidated incident information." /><Panel title="Information processing flow"><div className="panel-body flow">{flow.map((label, index) => <div className="flow-step" key={label}><span>0{index + 1}</span>{label}</div>)}</div></Panel><div className="metric-grid" style={{ marginTop: 18 }}>{metrics && Object.entries(metrics).map(([key, value]) => <div className="metric" key={key}><div className="num">{value}</div><div className="label">{key.replace(/([A-Z])/g, ' $1')}</div></div>)}</div><div className="detail-grid"><Panel title="Fusion review"><div className="panel-body incident-list">{items.filter((item) => item.fusion).map((item) => <article className="report-card" key={item.incident_id}><header><div><Link2 size={15} color="#67d4ce" style={{ verticalAlign: 'middle', marginRight: 7 }} /><b>Possible match · {item.incident_id}</b></div><span className="tag tag-medium">{item.fusion?.score}% FUSION</span></header><p>{item.report_count} related reports at {item.location.name}</p><ul className="reason-list">{item.fusion?.reasons.slice(0, 3).map((reason) => <li key={reason}><CheckCircle2 className="positive" size={15} />{reason}</li>)}</ul><Link className="linkish" style={{ display: 'block', marginTop: 12 }} to={`/incidents/${item.incident_id}`}>View incident</Link></article>)}</div></Panel><Panel title="Method note"><div className="panel-body"><div className="notice">Grouping explanations and scores are displayed from the intelligence API. The interface presents supporting reasons; it does not automatically conclude which conflicting claim is correct.</div></div></Panel></div></main> }
